language: node_js

sudo: false

branches:
  only:
  - master
  
before_install:
- openssl aes-256-cbc -K $encrypted_6d342e35c3d4_key -iv $encrypted_6d342e35c3d4_iv -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa 
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name 'blog'
- git config --global user.email blog@blog.com

install:
- npm install hexo-cli -g
- npm install

script:
- hexo clean
- hexo g
- hexo d